# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Default

steps:
- checkout: self
  fetchDepth: 0
  submodules: true
  fetchTags: true

- powershell: |
     $gitVersion = git describe --abbrev=0 --tags
     $buildNumber = $gitVersion + "." + $env:BUILD_BUILDNUMBER
     Write-Host "##vso[task.setvariable variable=buildVersion;isoutput=true]$buildNumber"
     Write-Host "Build number is $buildNumber"
  name: gitVersion

- task: NodeTool@0
  inputs:
    versionSpec: '18.19.x'
  displayName: 'Install Node.js'

- task: PowerShell@2
  displayName: 'npm install and build'
  inputs:
    targetType: 'inline'
    script: |
      npm install
      npm run build
    workingDirectory: '$(Build.Repository.LocalPath)\website'

- task: DotNetCoreCLI@2
  displayName: 'Publish SimpleIdServer'
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: false
    modifyOutputPath: false
    workingDirectory: '$(Build.Repository.LocalPath)\src\IdServer\SimpleIdServer.IdServer.Startup'

- task: DotNetCoreCLI@2
  displayName: 'Publish SimpleIdServer Website'
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: false
    modifyOutputPath: false
    workingDirectory: '$(Build.Repository.LocalPath)\src\IdServer\SimpleIdServer.IdServer.Website.Startup'

- task: DotNetCoreCLI@2
  displayName: 'Publish SCIM'
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: false
    modifyOutputPath: false
    workingDirectory: '$(Build.Repository.LocalPath)\src\Scim\SimpleIdServer.Scim.Startup'

- task: DotNetCoreCLI@2
  displayName: 'Publish Credential Issuer'
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: false
    modifyOutputPath: false
    workingDirectory: '$(Build.Repository.LocalPath)\src\CredentialIssuer\SimpleIdServer.CredentialIssuer.Startup'

- task: DotNetCoreCLI@2
  displayName: 'Publish Credential Issuer website'
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: false
    modifyOutputPath: false
    workingDirectory: '$(Build.Repository.LocalPath)\src\CredentialIssuer\SimpleIdServer.CredentialIssuer.Website.Startup'

- task: DotNetCoreCLI@2
  displayName: 'Publish Mobile application'
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '-f net7.0-android -c Release -p:AndroidKeyStore=true -p:AndroidSigningKeyStore=sidmobile.keystore -p:AndroidSigningKeyAlias=sidkey -p:AndroidSigningKeyPass=password -p:AndroidSigningStorePass=password'
    zipAfterPublish: false
    modifyOutputPath: false
    workingDirectory: '$(Build.Repository.LocalPath)\src\Mobile\SimpleIdServer.Mobile'

- task: CopyFiles@2
  displayName: 'Copy website'
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\website\build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\website'

- task: CopyFiles@2
  displayName: 'Copy SimpleIdServer'
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\src\IdServer\SimpleIdServer.IdServer.Startup\bin\Debug\net7.0\publish'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\simpleidserver'

- task: CopyFiles@2
  displayName: 'Copy SimpleIdServer website'
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\src\IdServer\SimpleIdServer.IdServer.Website.Startup\bin\Debug\net7.0\publish'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\simpleidserverwebsite'

- task: CopyFiles@2
  displayName: 'Copy SCIM'
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\src\Scim\SimpleIdServer.Scim.Startup\bin\Debug\net7.0\publish'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\scim'

- task: CopyFiles@2
  displayName: 'Copy Credential Issuer'
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\src\CredentialIssuer\SimpleIdServer.CredentialIssuer.Website\bin\Debug\net7.0\publish'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\credentialissuer'

- task: CopyFiles@2
  displayName: 'Copy Credential issuer website'
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\src\CredentialIssuer\SimpleIdServer.CredentialIssuer.Website.Startup\bin\Debug\net7.0\publish'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\credentialissuerwebsite'

- task: PublishBuildArtifacts@1
  displayName: 'Publish website artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\website'
    ArtifactName: 'website'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish simpleidserver artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\simpleidserver'
    ArtifactName: 'simpleidserver'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish simpleidserver website artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\simpleidserverwebsite'
    ArtifactName: 'simpleidserverwebsite'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish SCIM'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\scim'
    ArtifactName: 'scim'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Credential issuer'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\credentialissuer'
    ArtifactName: 'credentialissuer'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Credential issuer website'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\credentialissuerwebsite'
    ArtifactName: 'credentialissuerwebsite'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Mobile application'
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)\src\Mobile\SimpleIdServer.Mobile\bin\Release\net7.0-android\publish'
    ArtifactName: 'mobileApp'
    publishLocation: 'Container'