version: "3.9"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx
    ports:
      - '443:443'
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./compose/certificates:/etc/nginx/certs:ro
      - ./compose/proxy.conf:/etc/nginx/conf.d/customproxy.conf:ro
    networks:
      proxy_net:
        aliases:
          - idserver.localhost.com
          - scim.localhost.com
          - website.localhost.com
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
     - mssqldata:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD : "D54DE7hHpkG9"
    networks:
      proxy_net: null
  scim:
    image: simpleidserver/scim:4.0.5
    environment:
      VIRTUAL_HOST: "scim.localhost.com"
      ASPNETCORE_URLS : "http://*:80"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      StorageConfiguration__ConnectionString: "Data Source=db;Initial Catalog=Scim;TrustServerCertificate=True;User=sa;Password=D54DE7hHpkG9;"
    depends_on:
      - db
    networks:
      proxy_net: null
  idserver:
    image: simpleidserver/idserver:4.0.5
    environment:
      VIRTUAL_HOST: "idserver.localhost.com"
      ASPNETCORE_URLS : "http://*:80"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      DistributedCacheConfiguration__ConnectionString: "Data Source=db;Initial Catalog=IdServer;TrustServerCertificate=True;User=sa;Password=D54DE7hHpkG9;"
      StorageConfiguration__ConnectionString: "Data Source=db;Initial Catalog=IdServer;TrustServerCertificate=True;User=sa;Password=D54DE7hHpkG9;"
      SCIMBaseUrl: "https://scim.localhost.com"
      Authority: "https://idserver.localhost.com"
      SCIM__SCIMRepresentationsExtractionJobOptions__SCIMEdp: "Data Source=db;Initial Catalog=IdServer;TrustServerCertificate=True;User=sa;Password=D54DE7hHpkG9;"
    depends_on:
      - db
      - scim
    networks:
      proxy_net: null
  website:
    image: simpleidserver/website:4.0.5
    environment:
      VIRTUAL_HOST: "website.localhost.com"
      ASPNETCORE_URLS : "http://*:80"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      DefaultSecurityOptions__Issuer: "https://idserver.localhost.com/master"
      DefaultSecurityOptions__IgnoreCertificateError: "true"
      IdServerBaseUrl: "https://idserver.localhost.com"
      ScimBaseUrl: "https://scim.localhost.com"
    depends_on:
      - idserver
      - scim
    networks:
      proxy_net: null
networks:
  proxy_net:
    driver: bridge
volumes:
  mssqldata: